import { dehydrate, QueryClient, useQuery } from "@tanstack/react-query";
import { useEffect, useState } from "react";
import Head from "next/head";
import axios from "axios";
import Posts from "../components/Posts";
/**
 * first find out how to get data from reddit api
 * then make a request
 * how? using react-query and axios
 * we're only making a GET request so it'll be easy
 * I want a form to search for a subreddit
 * when the form is submitted, it will make a request to the reddit api with the form's value
 * then get the response and store it in the useQuery hook
 * it will have a loading, error, and actual content displayed
 * along with infinite gallery scrolling/loading?
 * clicking on an image will route to a more detailed page of the post or I could just route to the original link
 *
 *
 * Nice to have:
 * save the subreddit in a store and show it under the search as a recent search item
 * also have popular subreddits somewhere on the app
 *
 * data fetching at index.js
 * then pass it down to form component
 * after fetching, it gets passed up
 * then data passed down to posts component
 * clicking on an image goes to a post route with post component
 */

export default function Home() {
  const [posts, setPosts] = useState([]);
  const [subreddit, setSubreddit] = useState("webdev");

  useEffect(() => {
    // set state here r/{subreddit}/hot.json
    // might set category too r/boobs/{category}.json
    fetch(
      "https://www.reddit.com/r/boobs/hot.json?restrict_sr=true&include_over_18=on&raw_json=1"
    ).then((res) => {
      if (res.status !== 200) {
        console.warn("Warning: Something is wrong with the api.");
        return;
      }
      res.json().then((data) => {
        if (data != null) setPosts(data.data.children);
      });
    });
  }, [subreddit]);

  // failed at using react-query, i think i did this right, but i kept getting no data
  // const sub = useQuery(["subreddits"], getSubreddits)
  // );

  // const getSubreddits = async () => {
  //   const response = await axios.get(`https://www.reddit.com/r/webdev.json`);
  //   return response.data;
  // };
  return (
    <div>
      <Head>
        <title>Reddit Image Gallery with Next JS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Posts posts={posts} />
      </main>
    </div>
  );
}
